### ISSUE TITLE
Support Spring Configuration Property tooltips

### ISSUE THREAD

**Issue by ehp246** [ehp246/auf-jms#164]
```
me:
  ehp246:
    aufjms:
      dispatchlogger: 
        enabled: true
```
